### ISSUE TITLE
Segmentation fault (core dumped) on Ubuntu 16.04 Server and python3.5.2

### ISSUE THREAD

**Issue by mpouyandeh** [kislyuk/rehash#3]
I tried on two different system and same result  

Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
import pickle, rehash
 hasher = rehash.sha256(b"foo")
 state = pickle.dumps(hasher)
Segmentation fault (core dumped)
root@ddd:~#

**Comment by kislyuk** [comment]
Thanks for reporting. What's your OpenSSL version?

**Comment by kislyuk** [comment]
Also, what hardware architecture is this? amd64?

**Comment by mpouyandeh** [comment]
Output of `openssl version -v` cmd is "OpenSSL 1.0.2g  1 Mar 2016"
and output of `uname -m` cmd is "x86_64"

**Comment by mpouyandeh** [comment]
I think I should mention that I tested on the `OpenSSL 1.1.0f-fips  25 May 2017` Version  (on My local which is a fedora 27 workstation) and rehash is doing amazing job there

**Comment by kislyuk** [comment]
Thanks, I've reproduced the bug and am looking at what's different with this environment.

**Comment by kislyuk** [comment]
Thank you for reporting this. Being a segfault, obviously this bug was high priority.

I had incorrectly bisected the CPython source tree to determine the version numbers in which the OpenSSL bindings struct layout changes. The issue should now be fixed.

Released v0.3.1, please test.

**Comment by mpouyandeh** [comment]
It's working like a charm
Thank you for this excellent & unique library
